version: 2.1
jobs:
  pr_check_job:
    docker: 
      - image: circleci/openjdk:8-jdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Running pr_check_job" # run the `echo` command
      - run: 
          command: |
            cd Assignment3
            ./mvnw clean install 
  build:
    docker: 
      - image: circleci/openjdk:8-jdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Running build on master" # run the `echo` command
      - run: 
          command: |
            cd Assignment3
            ./mvnw clean install 
# mvn clean install tells Maven to do the clean phase in each module before running the install phase for each module.
workflows:
  version: 2
  pr_check:
    jobs:
      - pr_check_job
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
